apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    name: app-deploy
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-pod
      app: demo-app
  template:
    metadata:
      name: app-pod
      labels:
        name: app-pod
        app: demo-app
    spec:
      containers:
        - name: app
          image: 127322177288.dkr.ecr.us-west-1.amazonaws.com/intern/todoapp:ECR_IMAGE_TAG
          ports:
            - containerPort: 80
