apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: demo-app

  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: demo-app
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "intern_pass"
            - name: MYSQL_DATABASE
              value: "intern_db"
